apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gradle-pipeline
spec:
  params:
    - name: gitUrl
      description: Git repository url
  tasks:
    - name: pre-deploy
      taskRef:
        name: echo-hello
      params:
        - name:  "sname"
          value: "$(context.pipelineRun.name)"

    - name: setup
      runAfter:
        - pre-deploy
      taskRef:
        name: gradle
      params:
        - name: url
          value: "$(params.gitUrl)"
    - name: crds
      runAfter:
        - setup
      taskRef:
        name: gradle
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(tasks. parse-git-commit-id.results. git-commit-id)"
        - name: task
          value: cd_install_crd

    - name: operators
      runAfter:
        - setup
      taskRef:
        name: gradle
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(tasks. parse-git-commit-id.results. git-commit-id)"
        - name: task
          value: cd_operators

    - name: install
      timeout: "1h0m0s"
      runAfter:
        - crds
        - operators
      taskRef:
        name: gradle
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(tasks. parse-git-commit-id.results. git-commit-id)"
        - name: task
          value: cd_install

    - name: upgrade
      timeout: "0h10m0s"
      runAfter:
        - install
      taskRef:
        name: gradle
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(tasks. parse-git-commit-id.results. git-commit-id)"
        - name: task
          value: cd_install

    - name: report
      timeout: "0h10m0s"
      runAfter:
        - upgrade
        - install
      taskRef:
        name: gradle
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(tasks. parse-git-commit-id.results. git-commit-id)"
        - name: task
          value: cd_report