---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: print-date-pipeline
spec:
  tasks:
    - name: print-date-step
      taskRef:
        name: print-date
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  resources:
    - name: tekton-gradle-example-git
      type: git
  workspaces:
    - name: git-source
      description: The git repo
  params:
    - name: gitUrl
      description: Git repository url
    - name: gitRevision
      description: Git revision to check out
      default: master
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "."
        - name: deleteExisting
          value: "true"
    - name: build-docker
      taskRef:
        name: kaniko
    - name: run-gradle
      taskRef:
        name: gradle