apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: gradle-pipeline-run
spec:
  serviceAccountName: 'tekton-dashboard'
  pipelineRef:
    name: gradle-pipeline
  params:
    - name: gitUrl
      value: "https://github.com/dimetron/kind-tekton-gradle-example.git"